### PR TITLE
Fix issue #20 and add arm libraries

### PR DESCRIPTION
**Pull request by mwillers**
This fixes the issue for me.
Also adds arm libraries for macOS.

### CODE REVIEW

**Comment by gipert** [comment]
Hey Mike thank you. Can you also try to enable OSX wheels builds on GitHub? Have a look at the bottom of `pyproject.toml`.

**Comment by slwatkins** [comment]
@ssailer @gipert Is this ready to be merged? Hoping to be able to build this on my personal computer soon (macOS)

**Comment by gipert** [comment]
Just tagged a new version: https://github.com/legend-exp/pyfcutils/releases/tag/v0.2.3

Once the CI workflows are finished (https://github.com/legend-exp/pyfcutils/actions), you should be able to upgrade pyfcutils from pypi.

Please check if the new wheels are usable on MacOS

**Comment by slwatkins** [comment]
Thanks @gipert! I just tested building from source and using the wheel on PyPI, and both appear to compile and work perfectly. Tested by using build_raw in pygama on the legendtestdata FCIO file.

**Comment by mwillers** [comment]
Thanks Luigi!

**Pull request merged**
